apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: homework
spec:
  containers:
  - name: busybox
    image: busybox
    ports:
    - containerPort: 8000
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 300Mi
        cpu: 300m
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
  restartPolicy: Always