apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: homework
spec:
  storageClassName: minikube-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
