apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minikube-hostpath
  annotations:
    cpaas.io/creator: vyshegorodskiysp
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
#volumeBindingMode: WaitForFirstConsumer
